version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "measure-transfer-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bc2512b5"
s3_prefix = "measure-transfer-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
